2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_setup.py:_flush():79] Configure stats pid to 2209185
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_setup.py:_flush():79] Loading settings from /home/cr8dl-user/.config/wandb/settings
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_setup.py:_flush():79] Loading settings from /home/cr8dl-user/abhiram/ThinkTuning_v1/wandb/settings
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/home/cr8dl-user/abhiram/ThinkTuning_v1/train.py', 'program': '/home/cr8dl-user/abhiram/ThinkTuning_v1/train.py'}
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_init.py:_log_setup():532] Logging user logs to /home/cr8dl-user/abhiram/ThinkTuning_v1/wandb/run-20241016_002642-dftxfs0s/logs/debug.log
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_init.py:_log_setup():533] Logging internal logs to /home/cr8dl-user/abhiram/ThinkTuning_v1/wandb/run-20241016_002642-dftxfs0s/logs/debug-internal.log
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_init.py:init():617] calling init triggers
2024-10-16 00:26:42,351 INFO    MainThread:2209185 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {}
2024-10-16 00:26:42,352 INFO    MainThread:2209185 [wandb_init.py:init():667] starting backend
2024-10-16 00:26:42,352 INFO    MainThread:2209185 [wandb_init.py:init():671] sending inform_init request
2024-10-16 00:26:42,354 INFO    MainThread:2209185 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-16 00:26:42,354 INFO    MainThread:2209185 [wandb_init.py:init():684] backend started and connected
2024-10-16 00:26:42,362 INFO    MainThread:2209185 [wandb_init.py:init():779] updated telemetry
2024-10-16 00:26:42,377 INFO    MainThread:2209185 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-16 00:26:42,516 ERROR   MainThread:2209185 [wandb_init.py:init():838] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-10-16 00:26:42,517 ERROR   MainThread:2209185 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "/home/cr8dl-user/abhiram/ilt/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1252, in init
    return wi.init()
  File "/home/cr8dl-user/abhiram/ilt/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-10-16 00:26:42,689 WARNING MsgRouterThr:2209185 [router.py:message_loop():77] message_loop has been closed
